### ISSUE TITLE
del-cls 设置后无效

### ISSUE THREAD

**Issue by dengxiaozhen** [Jmingzi/vue-slip-delete#7]
```
del-cls="del-button"
```
```css
.del-button{
  font-size: 16px;
}
```
无法覆盖默认样式
